# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/thanos/Dev/Python/ui/guitar.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 521)
        MainWindow.setMinimumSize(QtCore.QSize(360, 0))
        MainWindow.setMaximumSize(QtCore.QSize(390, 16777215))
        MainWindow.setStyleSheet("background-color: white;")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frmEqFrame = QtWidgets.QFrame(self.centralwidget)
        self.frmEqFrame.setMinimumSize(QtCore.QSize(0, 200))
        self.frmEqFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmEqFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmEqFrame.setObjectName("frmEqFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frmEqFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.bar1 = QtWidgets.QLabel(self.frmEqFrame)
        self.bar1.setMaximumSize(QtCore.QSize(16777215, 0))
        self.bar1.setText("")
        self.bar1.setPixmap(QtGui.QPixmap(":/svg/svg/bar.svg"))
        self.bar1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.bar1.setObjectName("bar1")
        self.verticalLayout_8.addWidget(self.bar1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem2)
        self.bar2 = QtWidgets.QLabel(self.frmEqFrame)
        self.bar2.setMaximumSize(QtCore.QSize(16777215, 0))
        self.bar2.setText("")
        self.bar2.setPixmap(QtGui.QPixmap(":/svg/svg/bar.svg"))
        self.bar2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.bar2.setObjectName("bar2")
        self.verticalLayout_16.addWidget(self.bar2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_16)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem3)
        self.bar3 = QtWidgets.QLabel(self.frmEqFrame)
        self.bar3.setMaximumSize(QtCore.QSize(16777215, 0))
        self.bar3.setText("")
        self.bar3.setPixmap(QtGui.QPixmap(":/svg/svg/bar.svg"))
        self.bar3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.bar3.setObjectName("bar3")
        self.verticalLayout_15.addWidget(self.bar3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem4)
        self.bar4 = QtWidgets.QLabel(self.frmEqFrame)
        self.bar4.setMaximumSize(QtCore.QSize(16777215, 0))
        self.bar4.setText("")
        self.bar4.setPixmap(QtGui.QPixmap(":/svg/svg/bar.svg"))
        self.bar4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.bar4.setObjectName("bar4")
        self.verticalLayout_14.addWidget(self.bar4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_14)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem5)
        self.bar5 = QtWidgets.QLabel(self.frmEqFrame)
        self.bar5.setMaximumSize(QtCore.QSize(16777215, 0))
        self.bar5.setText("")
        self.bar5.setPixmap(QtGui.QPixmap(":/svg/svg/bar.svg"))
        self.bar5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.bar5.setObjectName("bar5")
        self.verticalLayout_12.addWidget(self.bar5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem6)
        self.bar6 = QtWidgets.QLabel(self.frmEqFrame)
        self.bar6.setMaximumSize(QtCore.QSize(16777215, 0))
        self.bar6.setText("")
        self.bar6.setPixmap(QtGui.QPixmap(":/svg/svg/bar.svg"))
        self.bar6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.bar6.setObjectName("bar6")
        self.verticalLayout_11.addWidget(self.bar6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.bar7 = QtWidgets.QLabel(self.frmEqFrame)
        self.bar7.setMaximumSize(QtCore.QSize(16777215, 0))
        self.bar7.setText("")
        self.bar7.setPixmap(QtGui.QPixmap(":/svg/svg/bar.svg"))
        self.bar7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.bar7.setObjectName("bar7")
        self.verticalLayout_5.addWidget(self.bar7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_10.addWidget(self.frmEqFrame)
        self.frmKeyFreqInfoFrame = QtWidgets.QFrame(self.centralwidget)
        self.frmKeyFreqInfoFrame.setStyleSheet("background-color:#fde9f5;\n"
"background-color:white;\n"
"border-radius:10px;\n"
"")
        self.frmKeyFreqInfoFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmKeyFreqInfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmKeyFreqInfoFrame.setObjectName("frmKeyFreqInfoFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frmKeyFreqInfoFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lblKey = QtWidgets.QLabel(self.frmKeyFreqInfoFrame)
        font = QtGui.QFont()
        font.setFamily("Lato ExtraBold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.lblKey.setFont(font)
        self.lblKey.setStyleSheet("color: #ff9e0d;\n"
"font-size:80px;\n"
"font-weight:900;\n"
"margin:0 0;")
        self.lblKey.setAlignment(QtCore.Qt.AlignCenter)
        self.lblKey.setObjectName("lblKey")
        self.verticalLayout_9.addWidget(self.lblKey)
        self.lblFreq = QtWidgets.QLabel(self.frmKeyFreqInfoFrame)
        self.lblFreq.setStyleSheet("font-weight:300;")
        self.lblFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFreq.setObjectName("lblFreq")
        self.verticalLayout_9.addWidget(self.lblFreq)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout_10.addWidget(self.frmKeyFreqInfoFrame)
        self.frmMultiBtnFrame = QtWidgets.QFrame(self.centralwidget)
        self.frmMultiBtnFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.frmMultiBtnFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmMultiBtnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmMultiBtnFrame.setObjectName("frmMultiBtnFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmMultiBtnFrame)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.wgtAuto = QtWidgets.QWidget(self.frmMultiBtnFrame)
        self.wgtAuto.setObjectName("wgtAuto")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wgtAuto)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblAutoIcon = QtWidgets.QLabel(self.wgtAuto)
        self.lblAutoIcon.setText("")
        self.lblAutoIcon.setPixmap(QtGui.QPixmap(":/svg/svg/cursor.svg"))
        self.lblAutoIcon.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblAutoIcon.setObjectName("lblAutoIcon")
        self.verticalLayout_2.addWidget(self.lblAutoIcon)
        self.btnAuto = QtWidgets.QPushButton(self.wgtAuto)
        self.btnAuto.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(37)
        self.btnAuto.setFont(font)
        self.btnAuto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAuto.setStyleSheet("color: #ff9e0d;\n"
"background-color: #e3e3e3;\n"
"border:0px solid white;\n"
"border-radius:15px;\n"
"font-size:11px;\n"
"padding:0 10px;\n"
"font-weight:300;")
        self.btnAuto.setFlat(False)
        self.btnAuto.setObjectName("btnAuto")
        self.verticalLayout_2.addWidget(self.btnAuto)
        self.horizontalLayout_2.addWidget(self.wgtAuto)
        self.wgtLoFi = QtWidgets.QWidget(self.frmMultiBtnFrame)
        self.wgtLoFi.setObjectName("wgtLoFi")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.wgtLoFi)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblLoFiIcon = QtWidgets.QLabel(self.wgtLoFi)
        self.lblLoFiIcon.setEnabled(True)
        self.lblLoFiIcon.setStyleSheet("")
        self.lblLoFiIcon.setText("")
        self.lblLoFiIcon.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblLoFiIcon.setObjectName("lblLoFiIcon")
        self.verticalLayout_3.addWidget(self.lblLoFiIcon)
        self.btnLoFi = QtWidgets.QPushButton(self.wgtLoFi)
        self.btnLoFi.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(37)
        self.btnLoFi.setFont(font)
        self.btnLoFi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLoFi.setStyleSheet("background-color: #e3e3e3;\n"
"border:0px solid white;\n"
"border-radius:15px;\n"
"font-size:11px;\n"
"padding:0 10px;\n"
"font-weight:300;")
        self.btnLoFi.setFlat(False)
        self.btnLoFi.setObjectName("btnLoFi")
        self.verticalLayout_3.addWidget(self.btnLoFi)
        self.horizontalLayout_2.addWidget(self.wgtLoFi)
        self.wgtMiFi = QtWidgets.QWidget(self.frmMultiBtnFrame)
        self.wgtMiFi.setObjectName("wgtMiFi")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.wgtMiFi)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblMiFiIcon = QtWidgets.QLabel(self.wgtMiFi)
        self.lblMiFiIcon.setText("")
        self.lblMiFiIcon.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblMiFiIcon.setObjectName("lblMiFiIcon")
        self.verticalLayout_4.addWidget(self.lblMiFiIcon)
        self.btnMiFi = QtWidgets.QPushButton(self.wgtMiFi)
        self.btnMiFi.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(37)
        self.btnMiFi.setFont(font)
        self.btnMiFi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMiFi.setStyleSheet("background-color: #e3e3e3;\n"
"border:0px solid white;\n"
"border-radius:15px;\n"
"font-size:11px;\n"
"padding:0 10px;\n"
"font-weight:300;")
        self.btnMiFi.setFlat(False)
        self.btnMiFi.setObjectName("btnMiFi")
        self.verticalLayout_4.addWidget(self.btnMiFi)
        self.horizontalLayout_2.addWidget(self.wgtMiFi)
        self.wgtHiFi = QtWidgets.QWidget(self.frmMultiBtnFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgtHiFi.sizePolicy().hasHeightForWidth())
        self.wgtHiFi.setSizePolicy(sizePolicy)
        self.wgtHiFi.setObjectName("wgtHiFi")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.wgtHiFi)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lblHiFiIcon = QtWidgets.QLabel(self.wgtHiFi)
        self.lblHiFiIcon.setText("")
        self.lblHiFiIcon.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblHiFiIcon.setObjectName("lblHiFiIcon")
        self.verticalLayout_7.addWidget(self.lblHiFiIcon)
        self.btnHiFi = QtWidgets.QPushButton(self.wgtHiFi)
        self.btnHiFi.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(37)
        self.btnHiFi.setFont(font)
        self.btnHiFi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHiFi.setStyleSheet("background-color: #e3e3e3;\n"
"border:0px solid white;\n"
"border-radius:15px;\n"
"font-size:11px;\n"
"padding:0 10px;\n"
"font-weight:300;")
        self.btnHiFi.setFlat(False)
        self.btnHiFi.setObjectName("btnHiFi")
        self.verticalLayout_7.addWidget(self.btnHiFi)
        self.horizontalLayout_2.addWidget(self.wgtHiFi)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.verticalLayout_10.addWidget(self.frmMultiBtnFrame)
        self.frmTuningBtnFrame = QtWidgets.QFrame(self.centralwidget)
        self.frmTuningBtnFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmTuningBtnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmTuningBtnFrame.setObjectName("frmTuningBtnFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frmTuningBtnFrame)
        self.horizontalLayout_4.setContentsMargins(-1, 8, -1, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.btnTuning = QtWidgets.QPushButton(self.frmTuningBtnFrame)
        self.btnTuning.setMinimumSize(QtCore.QSize(320, 40))
        self.btnTuning.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnTuning.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(8, 255, 68, 255), stop:1 rgba(172, 255, 1, 255));\n"
"border:0px;\n"
"color:white;\n"
"text-transform:uppercase;\n"
"letter-spacing:10px;\n"
"border-radius:5px;\n"
"font-size:10px;")
        self.btnTuning.setObjectName("btnTuning")
        self.horizontalLayout_4.addWidget(self.btnTuning)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.verticalLayout_10.addWidget(self.frmTuningBtnFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 22))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLight_Mode = QtWidgets.QAction(MainWindow)
        self.actionLight_Mode.setObjectName("actionLight_Mode")
        self.actionDark_Mode = QtWidgets.QAction(MainWindow)
        self.actionDark_Mode.setObjectName("actionDark_Mode")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOptions.addAction(self.actionLight_Mode)
        self.menuOptions.addAction(self.actionDark_Mode)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionInstructions)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Guitar Tunner"))
        self.lblKey.setText(_translate("MainWindow", "A"))
        self.lblFreq.setText(_translate("MainWindow", "( 0 Hz)"))
        self.btnAuto.setText(_translate("MainWindow", "Auto"))
        self.btnLoFi.setText(_translate("MainWindow", "Low Freq"))
        self.btnMiFi.setText(_translate("MainWindow", "Mid Freq"))
        self.btnHiFi.setText(_translate("MainWindow", "High Freq"))
        self.btnTuning.setText(_translate("MainWindow", "Start Tuning"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLight_Mode.setText(_translate("MainWindow", "Light Mode"))
        self.actionDark_Mode.setText(_translate("MainWindow", "Dark Mode"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
import resoruces_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
